/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2015-12-29 22:58:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLEncoder;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.Connection;
import java.util.Properties;

public final class data_005fretrieval_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header2.html", Long.valueOf(1451371349223L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link rel='stylesheet' href='css-style1.css'/>\n");
      out.write("        <link rel='stylesheet' href=\"style-header.css\"/>\n");
      out.write("        <style type=\"text/css\">\n");
      out.write("            table {width:100%;background-color: gray;}\n");
      out.write("            td,th {background-color: white;text-align: center;}\n");
      out.write("            th {background-color: darkgray; color:white;}\n");
      out.write("            th a:link {color:white;}\n");
      out.write("            th a:visited {color: white;}\n");
      out.write("        </style>\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      out.write("<!--\r\n");
      out.write("To change this template, choose Tools | Templates\r\n");
      out.write("and open the template in the editor.\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<div class=\"header menubar\">\r\n");
      out.write("    <div class=\"search_holder right\"><input class=\"short\" type=\"text\" placeholder=\"Search site\"/><input type=\"button\" class=\"button search\"/></div>\r\n");
      out.write("    <div class=\"headline left\">\r\n");
      out.write("        <h1 class=\"title\">Healthcare Information Center</h1>\r\n");
      out.write("        <h2 class=\"subtitle left right_radius\">Nongbuarawae Hospital</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"menu left left_radius\" onclick=\"window.location.href = 'index.jsp';\">Home</div>\r\n");
      out.write("    <div class=\"menu left right_radius\" onclick=\"window.location.href = 'semantic_search.jsp';\">Search & Analytics</div>\r\n");
      out.write("</div>\r\n");
      out.write("\n");
      out.write("        ");

            String order = "";
            order = (request.getParameter("order") != null) ? "order by " + request.getParameter("order") + " DESC" : "";
            Properties props = new Properties();
            props.load(getServletContext().getResourceAsStream("/WEB-INF/config.properties"));
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + props.getProperty("db_name"), props.getProperty("db_user"), props.getProperty("db_pass"));
            Statement stmt = conn.createStatement();
            ResultSet res2 = stmt.executeQuery("select count(id) from retrieval_instance where type='Person'");
            int countPer = (res2.next()) ? Integer.parseInt(res2.getString(1)) : 0;
            ResultSet res = stmt.executeQuery("select * from retrieval left join service on retrieval.service=service.id " + order + " where service>0");
            int count = 1;
        
      out.write("\n");
      out.write("        <!--<div class='right'><a href='#' onclick=\"window.open('data_retrieval_add.jsp', 'add task', 'width=400,height=400');\">Add New Task</a></div>-->\n");
      out.write("        <table id=\"retrieval_table\">\n");
      out.write("            <tr>\n");
      out.write("                <th>#</th>\n");
      out.write("                <th><a href=\"?order=date\">Provider</a></th>\n");
      out.write("                <th><a href=\"?order=date\">Date</a></th>\n");
      out.write("                <th><a href=\"?order=status\">Status</a></th>\n");
      out.write("                <th><a href=\"?order=instance\">Instances</a></th>\n");
      out.write("                <th><a href=\"?order=progress\">Progress</a></th>\n");
      out.write("                <th></th>\n");
      out.write("            </tr>\n");
      out.write("            ");

                while (!res.isClosed() && res.next()) {
                    int instance = Integer.parseInt(res.getString("instance"));
                    int progress = Integer.parseInt(res.getString("progress"));
            
      out.write("\n");
      out.write("            <tr>\n");
      out.write("                <td>");
      out.print(count);
      out.write("</td>\n");
      out.write("                <td>");
      out.print(res.getString("provider"));
      out.write("&nbsp;(");
      out.print(res.getString("operation1") + "/" + res.getString("operation2"));
      out.write(")</td>\n");
      out.write("                <td>");
      out.print(res.getString("date"));
      out.write("</td>\n");
      out.write("                <td>");
      out.print((res.getString("status").equals("processing")) ? "<font style='color:green'>" + res.getString("status") + "</font>" : "<font style='color:red'>" + res.getString("status") + "</font>");
      out.write("</td>\n");
      out.write("                <td><a href=\"javascript:void(0);\" onclick=\"if (confirm('sure?')) {\n");
      out.write("                            updateRows(this, '");
      out.print(res.getString("service"));
      out.write("', '");
      out.print(res.getString("operation1"));
      out.write("', '");
      out.print(URLEncoder.encode(res.getString("location")));
      out.write("', '");
      out.print(URLEncoder.encode(res.getString("targetNamespace")));
      out.write("');\n");
      out.write("                        }\">");
      out.print(instance);
      out.write("</a></td>\n");
      out.write("                <td>");
      out.print((progress < instance) ? "<font style='color:red;'>" + progress + "</font>" : "<font style='color:blue;'>" + progress + "</font>");
      out.write("</td>\n");
      out.write("                <td>\n");
      out.write("                    ");
if (!res.getString("status").equals("processing") && (progress < instance)) {
      out.write("\n");
      out.write("                    <a href=\"javascript:void(0);\" onclick=\"if (confirm('คุณต้องการเรียกข้อมูลตอนนี้?')) {\n");
      out.write("                                retrieveRows(this, '");
      out.print(res.getString("service"));
      out.write("', '");
      out.print(res.getString("operation2"));
      out.write("', '");
      out.print(progress);
      out.write("', '");
      out.print(instance);
      out.write("', '");
      out.print(URLEncoder.encode(res.getString("location")));
      out.write("', '");
      out.print(URLEncoder.encode(res.getString("targetNamespace")));
      out.write("', 'Person');\n");
      out.write("                            }\">");
      out.print((res.getString("status").equals("suspended")) ? "Resume" : "Start");
      out.write("</a>&nbsp;|&nbsp;\n");
      out.write("                    ");
}
      out.write("       \n");
      out.write("                    ");
if (progress > 0) {
      out.write("\n");
      out.write("                    <a href=\"javascript:void(0);\" onclick=\"if (confirm('คุณต้องการที่จะตั้งค่า Progress กลับไปที่ 0 หรือไม่?')) {\n");
      out.write("                                window.location.href = 'updateDB.jsp?redirect=data_retrieval.jsp&table=retrieval&key=service&service=");
      out.print(res.getString("service"));
      out.write("&progress=0';\n");
      out.write("                            }\">Clear</a>&nbsp;|&nbsp; \n");
      out.write("                    ");
}
      out.write("\n");
      out.write("                    <a href=\"javascript:void(0);\" onclick=\"if (confirm('คุณมั่นใจที่จะลบหรือไม่?')) {\n");
      out.write("                                window.location.href = 'deleteDB.jsp?redirect=data_retrieval.jsp&table=retrieval&where=date&value=");
      out.print(res.getString("date"));
      out.write("';\n");
      out.write("                            }\">Delete</a>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("            ");

                    count++;
                }
      out.write("\n");
      out.write("            <tr style=\"font-weight: bold;\">\n");
      out.write("                <td colspan=\"2\" style=\"background-color: #eaeaea;\">Number of Persons (Unique PID)</td><td colspan=\"4\" style=\"background-color: #eaeaea;\">");
      out.print(countPer);
      out.write("</td>\n");
      out.write("                <td colspan=\"2\" style=\"background-color: #eaeaea;\"><a href=\"javascript:void(0);\" onclick=\"if (confirm('คุณต้องการที่จะล้าง PID หรือไม่?')) {\n");
      out.write("                            window.location.href = 'deleteDB.jsp?redirect=data_retrieval.jsp&table=retrieval_instance&where=type&value=Person';\n");
      out.write("                        }\">Clear Instances</a></td>\n");
      out.write("            </tr>\n");
      out.write("        </table>\n");
      out.write("    </body>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        var ajaxloader = document.createElement(\"IMG\");\n");
      out.write("        ajaxloader.setAttribute(\"src\", \"images/ajax-loader.gif\");\n");
      out.write("        function getHTTP() {\n");
      out.write("            var obj = null;\n");
      out.write("            if (window.XMLHttpRequest) {\n");
      out.write("                obj = new XMLHttpRequest();\n");
      out.write("            } else {\n");
      out.write("                obj = new ActiveXObject(\"Microsoft.XMLHTTP\");\n");
      out.write("            }\n");
      out.write("            return obj;\n");
      out.write("        }\n");
      out.write("        function updateRows(nd, id, oper, loc, ns) {\n");
      out.write("            var httpObj = getHTTP();\n");
      out.write("            if (httpObj != null) {\n");
      out.write("                removeChilds(nd);\n");
      out.write("                nd.appendChild(ajaxloader);\n");
      out.write("                httpObj.open(\"POST\", \"data_retrieval_update_rows.jsp?\" + Math.random(), true);\n");
      out.write("                httpObj.onreadystatechange = function() {\n");
      out.write("                    if (httpObj.readyState == 4 && httpObj.status == 200) {\n");
      out.write("                        window.location.href = '';\n");
      out.write("                    }\n");
      out.write("                };\n");
      out.write("                httpObj.setRequestHeader(\"Content-type\", \"application/x-www-form-urlencoded\");\n");
      out.write("                httpObj.send(\"id=\" + id + \"&oper=\" + oper + \"&host=\" + loc + \"&ns=\" + ns);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        function retrieveRows(nd, id, oper, offset, limit, loc, ns, cls) {\n");
      out.write("            var httpObj = getHTTP();\n");
      out.write("            if (httpObj != null) {\n");
      out.write("                removeChilds(nd);\n");
      out.write("                nd.appendChild(ajaxloader);\n");
      out.write("                httpObj.open(\"POST\", \"data_retrieval_exec.jsp?\" + Math.random(), true);\n");
      out.write("                httpObj.onreadystatechange = function() {\n");
      out.write("                    if (httpObj.readyState == 4 && httpObj.status == 200) {\n");
      out.write("                        //alert(httpObj.responseText);\n");
      out.write("                        alert('Retrieve persons\\' id succesfull!');\n");
      out.write("                        window.location.href = '';\n");
      out.write("                    }\n");
      out.write("                };\n");
      out.write("                httpObj.setRequestHeader(\"Content-type\", \"application/x-www-form-urlencoded\");\n");
      out.write("                httpObj.send(\"id=\" + id + \"&oper=\" + oper + \"&offset=\" + offset + \"&limit=\" + limit + \"&host=\" + loc + \"&ns=\" + ns + \"&class=\" + cls);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        function removeChilds(nd) {\n");
      out.write("            for (var i = 0; i < nd.childNodes.length; i++) {\n");
      out.write("                nd.removeChild(nd.childNodes[i]);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
