/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2015-12-29 06:54:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import java.sql.DriverManager;
import java.sql.Connection;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("        <style type=\"text/css\">\n");
      out.write("            * {margin:0;}\n");
      out.write("            body {text-align: center;}\n");
      out.write("            div {width:300px;border:1px solid black; margin:0 auto; margin-top: 100px;border-radius: 5pt;padding:10px;}\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");


            String outmsg = "";
            Properties props = new Properties();//read properties file
            props.load(getServletContext().getResourceAsStream("WEB-INF/config.properties"));

            try {
                Class.forName("com.mysql.jdbc.Driver");//connect mysql
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + props.getProperty("db_name"), props.getProperty("db_user"), props.getProperty("db_pass"));
                Statement stmt = conn.createStatement();
                ResultSet res1 = stmt.executeQuery("select * from users where username='" + request.getParameter("username") + "' and password=md5('" + request.getParameter("password") + "')");
                int chk = 0;
                while (res1.next()) {
                    session.setAttribute("username", res1.getString("username"));
                    session.setAttribute("password", request.getParameter("password"));
                    session.setAttribute("userclass", res1.getString("class"));
                    session.setAttribute("userfirstname", res1.getString("firstname"));
                    session.setAttribute("userlastname", res1.getString("lastname"));
                    chk++;
                }
                if (chk > 0) {
                    outmsg = "<script type=\"text/javascript\">window.location.href = 'index.jsp';</script>";
                } else {
                    outmsg = "<div><h3>เข้าสู่ระบบผิดพลาด</h3><p>Invalid Username or Password.</p><a href='index.jsp'>BACK</a></div>";
                }
            } catch (Exception e) {
                outmsg = "<div><h3>เข้าสู่ระบบผิดพลาด</h3><p>ไม่สามารถติดต่อกับฐานข้อมูล</p><a href='index.jsp'>BACK</a></div>";
            }
        
      out.write("\n");
      out.write("        ");
      out.print(outmsg);
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
