/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2015-12-29 22:58:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.sql.ResultSetMetaData;
import java.sql.ResultSet;
import java.util.Properties;
import java.sql.DriverManager;
import java.sql.Connection;

public final class manage_005fusers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header2.html", Long.valueOf(1451371349223L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css-style1.css\"/>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"style-header.css\"/>\n");
      out.write("        <style type=\"text/css\">\n");
      out.write("            table {width:100%;background-color: gray;}\n");
      out.write("            td,th {text-align: center;}\n");
      out.write("            th {background-color: lightgray;font-weight: bold;}\n");
      out.write("            .rowstyle1 {background-color: beige;}\n");
      out.write("            .rowstyle2 {background-color:lightcyan ;}\n");
      out.write("        </style>\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            function removeUser(id) {\n");
      out.write("                if (confirm('คุณมั่นใจที่จะลบรายการหรือไม่?')) {\n");
      out.write("                    window.location.href = 'deleteDB.jsp?table=users&where=username&value=' + id + '&redirect=manage_users.jsp';\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      out.write("<!--\r\n");
      out.write("To change this template, choose Tools | Templates\r\n");
      out.write("and open the template in the editor.\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<div class=\"header menubar\">\r\n");
      out.write("    <div class=\"search_holder right\"><input class=\"short\" type=\"text\" placeholder=\"Search site\"/><input type=\"button\" class=\"button search\"/></div>\r\n");
      out.write("    <div class=\"headline left\">\r\n");
      out.write("        <h1 class=\"title\">Healthcare Information Center</h1>\r\n");
      out.write("        <h2 class=\"subtitle left right_radius\">Nongbuarawae Hospital</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"menu left left_radius\" onclick=\"window.location.href = 'index.jsp';\">Home</div>\r\n");
      out.write("    <div class=\"menu left right_radius\" onclick=\"window.location.href = 'semantic_search.jsp';\">Search & Analytics</div>\r\n");
      out.write("</div>\r\n");
      out.write("\n");
      out.write("        ");

            int offset = 0;
            int limit = 20;
            Properties props = new Properties();
            props.load(getServletContext().getResourceAsStream("WEB-INF/config.properties"));
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + props.getProperty("db_name"), props.getProperty("db_user"), props.getProperty("db_pass"));
            ResultSet res = conn.createStatement().executeQuery("select * from users limit " + offset + "," + limit);
            ResultSetMetaData meta = res.getMetaData();
        
      out.write("\n");
      out.write("        <h3>List of Users</h3>\n");
      out.write("        <a class='right' href='edit_user.jsp?action=insert'>Add User</a>\n");
      out.write("        <h6 id=\"count_users\"> Users</h6>\n");
      out.write("        <table id=\"users_table\">\n");
      out.write("            <tr>\n");
      out.write("                ");

                    ArrayList<String> cols = new ArrayList<String>();
                    out.println("<th></th>");
                    for (int i = 1; i <= meta.getColumnCount(); i++) {
                        out.println("<th>" + meta.getColumnName(i) + "</th>");
                        cols.add(meta.getColumnName(i));
                    }
                    out.println("<th></th>");
                
      out.write("\n");
      out.write("            </tr>\n");
      out.write("            ");

                int count_users = 0;
                while (res.next()) {
                    int num = ((count_users + 2) % 2 == 0) ? 1 : 2;
                    out.println("<tr class='rowstyle" + num + "'><td>" + (count_users + 1) + "</td>");
                    for (String s : cols) {
                        String v = (s.equals("password")) ? "****" : res.getString(s);
                        v = (v.equals("")) ? "-" : v;
                        out.println("<td>" + v + "</td>");
                    }
                    String del = (res.getString("username").equals(session.getAttribute("username"))) ? "" : " | <a href='#' onclick=\"removeUser('" + res.getString("username") + "');\">Delete</a></td>";
                    out.println("<td><a href='edit_user.jsp?user=" + res.getString("username") + "'>Edit</a>" + del + "</tr>");
                    count_users += 1;
                }
            
      out.write("\n");
      out.write("            <script type=\"text/javascript\">document.getElementById('count_users').innerHTML = '");
      out.print(count_users);
      out.write(" Users';</script>\n");
      out.write("        </table>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
