/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-01-15 02:33:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.Connection;
import java.util.Properties;

public final class semantic_005fsearch_005fsetlabel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    ");

        request.setCharacterEncoding("UTF-8");
        String lb = "";
		String sparql = "";
		String sparqltxt = "";
		String sparqlbtntxt = "";
        if (request.getParameter("id") != null) {
            Properties props = new Properties();
            props.load(getServletContext().getResourceAsStream("WEB-INF/config.properties"));
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + props.getProperty("db_name"), props.getProperty("db_user"), props.getProperty("db_pass"));
            Statement stmt = conn.createStatement();
            ResultSet res = stmt.executeQuery("select * from analytic where id='" + request.getParameter("id") + "'");
            if (res.next()) {
                lb = res.getString("label");
				sparql = res.getString("sparql");
            }
            stmt.close();
			sparqltxt = "<textarea id='fullsparql' style='width:100%;height:400px;' name='sparql'>"+sparql+"</textarea>";
			sparqlbtntxt = "window.opener.document.getElementById('save_analytic').sparql.value = document.getElementById('fullsparql').value;";
        }
    
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <h3>Label for Analytic</h3>\n");
      out.write("        <input id=\"analytic_label\" type=\"text\" name=\"label\" value=\"");
      out.print(lb);
      out.write("\" style=\"width:300px;\"/>\n");
      out.write("\t\t");
      out.print(sparqltxt);
      out.write("\n");
      out.write("        <button type=\"button\" onclick=\"window.close();\">ยกเลิก</button>\n");
      out.write("        <button type=\"button\" onclick=\"window.opener.document.getElementById('save_analytic').label.value = document.getElementById('analytic_label').value;");
      out.print(sparqlbtntxt);
      out.write("\n");
      out.write("                window.opener.document.getElementById('save_analytic').submit();\n");
      out.write("                window.close();\">ตกลง</button>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
